import Head from 'next/head'
import AddressForm from '@/components/AddressForm'
import Footer from '@/components/Footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Weather Forecast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex flex-col h-screen justify-between'>
        <main className="container m-auto p-4">
          <h1 className='text-center p-8'>Weather Forecast</h1>
          <AddressForm />
        </main>
        <Footer />
      </div>
    </>
  )
}
