import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.scss'
import { InferGetServerSidePropsType } from 'next'
import { GetServerSideProps } from 'next'

const inter = Inter({ subsets: ['latin'] })

type Data = {}

export const getServerSideProps: GetServerSideProps<{ data: Data }> = async () => {

  const data = await fetch('https://geocoding.geo.census.gov/geocoder/locations/onelineaddress?address=4600+Silver+Hill+Rd%2C+Washington%2C+DC+20233&benchmark=2020&format=json')
    .then(response => {
      if (!response.ok) {
        throw new Error('Geocoder request error')
      }
      return response.json()
    })
    .then(data => data)
    .catch(error => JSON.stringify(error))

  return {
    props: {
      data,
    },
  }
}

export default function Home({ data }: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Weather Forecast</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <pre>
          {JSON.stringify(data)}
        </pre>
      </main>
    </>
  )
}
